"""empty message

Revision ID: 0c0ded9a5b12
Revises: ffddcf95ea49
Create Date: 2020-08-27 14:58:25.055088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0ded9a5b12'
down_revision = 'ffddcf95ea49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_name', sa.String(length=20), nullable=False),
    sa.Column('w_id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('cmcontent', sa.Text(), nullable=False),
    sa.Column('cmtime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_c_id'), 'comment', ['c_id'], unique=False)
    op.create_index(op.f('ix_comment_u_name'), 'comment', ['u_name'], unique=False)
    op.create_index(op.f('ix_comment_w_id'), 'comment', ['w_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_w_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_u_name'), table_name='comment')
    op.drop_index(op.f('ix_comment_c_id'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
