"""empty message

Revision ID: ce89b4506e68
Revises: 1eb7b16e467e
Create Date: 2020-08-24 21:19:30.661313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce89b4506e68'
down_revision = '1eb7b16e467e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wbname', sa.String(length=20), nullable=False),
    sa.Column('u_name', sa.String(length=20), nullable=True),
    sa.Column('wbtime', sa.Date(), nullable=True),
    sa.Column('wbcontent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb')
    # ### end Alembic commands ###
