"""empty message

Revision ID: df08d9c90db3
Revises: ce89b4506e68
Create Date: 2020-08-24 21:32:10.823401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df08d9c90db3'
down_revision = 'ce89b4506e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('男', '女', '保密'), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wbname', sa.String(length=20), nullable=False),
    sa.Column('u_name', sa.String(length=20), nullable=True),
    sa.Column('wbtime', sa.Date(), nullable=True),
    sa.Column('wbcontent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb')
    op.drop_table('user')
    # ### end Alembic commands ###
